import java.lang.String;

public class VariableNamesTheme {
    public static void main(String[] args) {
        System.out.println("1. РАЗНЫЕ ПЕРЕМЕННЫЕ");
        int digit = 5;
        System.out.println("Цифра = " + digit);
        int digitSum = 5 + 1987;
        System.out.println("Сумма чисел = " + digitSum);
        int numbersProduct = 5 * 1987;
        System.out.println("Произведение чисел = " + numbersProduct);
        int maxNumber = 5;
        System.out.println("максимальное число = " + maxNumber);
        int tensNumber = 5;
        System.out.println("количество десятков = " + tensNumber);
        float dogWeight = 5.1f;
        System.out.println("вес собаки = " + dogWeight);
        int originalNumber = 1;
        System.out.println("исходное число = " + originalNumber);
        float depositPercentage = 10.4f;
        System.out.println("процент по вкладу = " + depositPercentage);
        char symbolAnd = '&';
        System.out.println("символ & = " + symbolAnd);
        int errorCode = 404;
        System.out.println("код ошибки = " + errorCode);
        String messageType = "text";
        System.out.println("тип сообщения = " + messageType);
        int zerosNumber = 2;
        System.out.println("число нулей = " + zerosNumber);
        boolean uniqueNumber = false;
        System.out.println("уникальное число = " + uniqueNumber);
        int randomNumber = 4;
        System.out.println("случайное число = " + randomNumber);
        String mathExpression = "2 + 2";
        System.out.println("математическое выражение = " + mathExpression);
        String gameScore = "2:2";
        System.out.println("счет в игре = " + gameScore);
        int maxLength = 4000;
        System.out.println("максимальная длина = " + maxLength);
        String menuItem = "Open";
        System.out.println("пункт меню = " + menuItem);
        float coffeePrice = 9.99f;
        System.out.println("стоимость кофе = " + coffeePrice);
        String startDate = "01.03.2026";
        System.out.println("начальная дата = " + startDate);
        int rangeEnd = 999999;
        System.out.println("окончание диапазона = " + rangeEnd);
        String monthEmployeeName = "Ksenia";
        System.out.println("имя работника месяца = " + monthEmployeeName);
        String titleEbookName = "Atomic habits";
        System.out.println("название электронной книги = " + titleEbookName);
        char size = 'S';
        System.out.println("размер = " + size);
        String capacity = "1 m3";
        System.out.println("вместимость = " + capacity);
        int counter = 11;
        System.out.println("счетчик = " + counter);
        String filePath = "C:\\Users\\KSU\\Documents\\Java\\StartJava";
        System.out.println("путь до файла = " + filePath);
        int numberQuantityInString = 0;
        System.out.println("количество чисел в строке = " + numberQuantityInString);
        System.out.println("2. BOOLEAN-ПЕРЕМЕННЫЕ");
        boolean isHundredsEqual = false;
        System.out.println("сотни равны? " + isHundredsEqual);
        boolean isComputerOn = true;
        System.out.println("компьютер включен? " + isComputerOn);
        boolean hasEqualNumbers = false;
        System.out.println("есть равные цифры? " + hasEqualNumbers);
        boolean isServiceCreated = false;
        System.out.println("служба создана? " + isServiceCreated);
        boolean isFileEmpty = false;
        System.out.println("файл пустой? " + isFileEmpty);
        boolean isConnectionAtive = false;
        System.out.println("соединение активное? " + isConnectionAtive);
        boolean isNewOne = false;
        System.out.println("новый? " + isNewOne);
        boolean isEmailValid = true;
        System.out.println("электронная почта действительная? " + isEmailValid);
        boolean hasUniqueStrings = false;
        System.out.println("имеются уникальные строки = " + hasUniqueStrings);
        System.out.println("3. АББРЕВИАТУРЫ");
        String guid = "550e8400-e29b-41d4-a716-446655440000";
        System.out.println("старый universally unique identifier = " + guid);
        String ramManufacturer = "Samsung";
        System.out.println("производитель оперативной памяти = " + ramManufacturer);
        String hddCapacity = "500GB";
        System.out.println("емкость жесткого диска = " + hddCapacity);
        String http = "tcp";
        System.out.println("определение термина протокола передачи гипертекста = " + http);
        String url = "ya.ru";
        System.out.println("сокращенный uniform resource locator = " + url);
        String newClientId = "777";
        System.out.println("новый идентификатор клиента = " + newClientId);
        String asciiSymbolCount = "128";
        System.out.println("количество символов в american standard code for information interchange = " + 
                asciiSymbolCount);
    }
}
